### ISSUE TITLE
LCD Font Smoothing

### ISSUE THREAD

**Issue by kevinSuttle** [kevinSuttle/OSXDefaults#17]
<img width="660" alt="general" src="https://cloud.githubusercontent.com/assets/95672/10328561/3348e0bc-6c84-11e5-958a-95e7a496eb91.png">

I see two possible properties here. 

```bash
defaults read NSGlobalDomain AppleFontSmoothing
defaults read NSGlobalDomain AppleAntiAliasingThreshold
```

Not sure which is which. @mathiasbynens any ideas?

**Comment by mathiasbynens** [comment]
Hmm, what happens if you `defaults read > a`, then check the checkbox, then `defaults read > b` and `diff a b`? Does the diff include both properties?

**Comment by kevinSuttle** [comment]
`defaults read NSGlobalDomain AppleAntiAliasingThreshold` returns `4`
`defaults read NSGlobalDomain AppleFontSmoothing` isn't set by default. 

Neither seems to affect the checkbox, even after quitting System Preferences.

**Comment by kevinSuttle** [comment]
A bit of Googling shows that 1-4 is the range for `AppleFontSmoothing`, rather than a boolean for a checkbox. 
https://software.com/mac/tweaks/change-font-smoothing

Also, it appears that `AppleAntiAliasingThreshold` can take a large range of integers, in the form of font sizes (e.g. `16`), which denotes at which font size the anti-aliasing kicks in I suppose. You can also set this per application.

`defaults -currentHost write com.apple.safari AppleAntiAliasingThreshold -int 16`
http://ss64.com/osx/syntax-defaults.html

**Comment by kevinSuttle** [comment]
Confirmed `defaults -currentHost write -globalDomain AppleFontSmoothing -int 2` changes the checkbox selection to a dash. 
http://sayzlim.net/font-smoothing-non-retina-display/

**Comment by lucaorio** [comment]
@kevinSuttle Sorry Kevin, just a double check: `AppleAntiAliasingThreshold` default is at `4`, but what's the default value for `AppleFontSmoothing` (checkbox selected)?

**Comment by SteveJobzniak** [comment]
@lucaorio Things changed in El Capitan. It used to be default to 3. Now it's default to 2 (slightly crisper text everywhere for all Mac users at last).

AppleFontSmoothing's default is 2 in macOS Sierra. Confirmed by writing the per-app value and starting an app multiple times, taking screenshots of the appearance of each value, and then trying other values. I only wanted to change smoothing in Emacs so I use:

```
defaults write org.gnu.Emacs AppleFontSmoothing -int 0
```

Here are the possible values:

0 (or any other invalid value such as 4 or higher) = Disabled.
1 = Minimal
2 = Medium (default from El Capitan and forward)
3 = Strong (default in old versions of macOS)

Values from 4 and up all just map to the same behavior as 0. So there is no 4th option.

I suggest you try all of them (0-3) and decide which you like. To me, 1 looks the best. It doesn't suffer from the terribly distorted font shapes that 0 has, but it's still very light. Excellent for programming.

**Comment by SteveJobzniak** [comment]
![rero3](https://cloud.githubusercontent.com/assets/22373193/21125940/5934579c-c0e9-11e6-8834-a1a4f5731ac2.gif)

Enjoy this handy reference.

**Comment by SteveJobzniak** [comment]
I made an animation on my own, which is more helpful for programmers. This shows clearly why the best setting is 1 (having LCD subpixels, but at the lowest amount):

![lcd_emacsanim](https://cloud.githubusercontent.com/assets/22373193/21126920/85eb4e16-c0ef-11e6-9c24-bd87eefdfba4.gif)

**Comment by SteveJobzniak** [comment]
@lucaorio If you or someone else ever wants a handy reference that you can point to, I wrote one and uploaded it here, where it will stay hosted forever:

https://github.com/SteveJobzniak/spacemaxed/blob/master/spacemaxed/docs/02_MACTWEAKS.org

**Comment by rajington** [comment]
@ghost link is dead!

**Comment by IceMan81** [comment]
Sorry for raising a question on a closed question. 

Does anyone know how this font smoothing is different from colored subpixels - in the [TinkerTool](https://www.bresink.com/osx/TinkerTool.html) this is the _Enforce old style font smoothing if available_

![image](https://user-images.githubusercontent.com/1093778/78823414-7e099f00-7991-11ea-840a-c344a11f0e14.png)

I came across this ticket through one of the comments to my question [here](https://apple.stackexchange.com/questions/387140/what-is-the-difference-between-the-different-font-smoothing-levels-on-macos)
